wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1760652850.619197
    t:
      1:
      - 55
      - 86
      - 95
      - 105
      3:
      - 23
      4: 3.12.7
      5: 0.16.1
      8:
      - 2
      - 5
      13: darwin-arm64
